[common]
# frps 地址
server_addr = "0.0.0.0"
# frps 端口
server_port = 7000
# 授权令牌
token = "12345678"
# 你的代理名称
user = "bithot"
# 设置管理地址用于通过http api控制frpc的动作，例如reload
admin_addr = "127.0.0.1"
admin_port = 7400
admin_user = "admin"
admin_pwd = "admin"

[proxy]
[proxy.ssh]
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6001
[proxy.dns]
type = "udp"
local_ip = "114.114.114.114"
local_port = 53
remote_port = 6002
# Log配置
[log]
file = "./frps.log"
level = "info"