[common]
# frps 地址
server_addr = "0.0.0.0"
# frps 端口
server_port = 7000
# 授权令牌
token = "12345678"
user = "bithot"
[proxy]
[proxy.ssh]
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6001
[proxy.dns]
type = "udp"
local_ip = "114.114.114.114"
local_port = 53
remote_port = 6002
# Log配置
[log]
file = "./frps.log"
level = "info"